# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VoChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vo Chat
  pod 'Firebase', '~>3.17'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
  pod 'SVProgressHUD'
  pod 'ChameleonFramework'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
